export const LinkConstants = {
    TimeLinePath: "/timeline",
    ProjectDetailPath: "/projectdetail",
}

export const ApiPaths = {
    BasePath: "https://claimshackifappapi.azurewebsites.net/api/",
    Team: "release/planned",
    PastPath: "release/past",
}

export const ActionConstants = {
    TIMELINEPAGE_TAB_CHAGED: 'TIMELINEPAGE_TAB_CHAGED',
    TIMELINEPAGE_ISLOADING: 'TIMELINEPAGE_ISLOADING',
    TIMELINEPAGE_RECIEVE_DATA: 'TIMELINEPAGE_RECIEVE_DATA',
    TIMELINEPAGE_RECIEVE_PAST_DATA: 'TIMELINEPAGE_RECIEVE_PAST_DATA',
    TIMELINEPAGE_PROJECT_FILTER_CHANGED: 'TIMELINEPAGE_PROJECT_FILTER_CHANGED',
    TIMELINEPAGE_SUBSCRIBED_PROJECT_FILTER_CHANGED: 'TIMELINEPAGE_SUBSCRIBED_PROJECT_FILTER_CHANGED',
    TIMELINEPAGE_SEARCH_FILTER_CHANGED: 'TIMELINEPAGE_SEARCH_FILTER_CHANGED',
    TIMELINEPAGE_SIDES_CHANGED: 'TIMELINEPAGE_SIDES_CHANGED',



    PROJECTDETAILPAGE_FETCH_DATA: 'PROJECTDETAILPAGE_FETCH_DATA',
}